# TBA
name: Backend

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           
            - uses: actions/checkout@v2

            # Node.js (for package scripts)
            -   uses: actions/setup-node@v4
                with:
                    node-version: lts/*
                    
            # Python
            -   uses: actions/setup-python@v4
                with:
                    python-version: "3.10"

            -   uses: snok/install-poetry@v1
                with:
                    version: "1.7.1"
                    virtualenvs-create: true
                    virtualenvs-in-project: false
                    virtualenvs-path: ~/my-custom-path
                    installer-parallel: true

            # Install backend dependencies
            -   run: yarn install:backend

            # Run backend
            # -   run: yarn dev:backend